### ISSUE TITLE
Reformat

### ISSUE THREAD

**Issue by SalsaGal** [SalsaGal/unLoKable#1]
White space is very inconsistent, naming conventions are all over the place, just a bit daunting to actually fix.

**Comment by khanh130202** [comment]
Can you assign me this issue?

**Comment by SalsaGal** [comment]
Oh, uh sure you can also just make the change without being assigned. Try to stick to `snake_case` for as much as you can, and 4 spaces for tabs.

**Comment by khanh130202** [comment]
how to run this

**Comment by SalsaGal** [comment]
Uh, run `mkdir out` to make the output directory, then run `make` to compile changes, then `out/able` with the arguments as given in the usage menu

**Comment by SalsaGal** [comment]
Fixed by ea8d4b83290814fa4a78562689f40ab8386111cd, @khanh130202 don't worry about this anymore.
